import {ServiceHero,SolutionOverview,serviceFamily} from '../../../../components/ServiceLanding';
import {serviceGuidance} from '../../../../lib/service-guidance';
import type {Metadata} from 'next';
import {Callouts,ConversionBand,WhatsAppLink} from '../../../../components/ContactActions';
import {JsonLd,BreadcrumbData,siteUrl,ogDefaults} from '../../../../components/StructuredData';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowRight} from 'lucide-react';
import {services} from '../../../../lib/content';
import {Breadcrumb,PageHero,ServiceCard,CTA,Tag,Checklist,FAQ} from '../../../../components/Inner';
export const dynamicParams=false;
export function generateStaticParams(){return services.map(s=>({slug:s.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=services.find(x=>x.slug===slug);return s?{title:`${s.name} Services | Inventive Clicks`,description:s.summary,alternates:{canonical:`/services/${slug}`},openGraph:{...ogDefaults,title:`${s.name} Services | Inventive Clicks`,description:s.summary,url:`/services/${slug}`,type:"website"}}:{title:'Service not found'}}
export default async function Service({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(x=>x.slug===slug);if(!s)notFound();const guidance=serviceGuidance[slug];const related=guidance.related.map(slug=>services.find(s=>s.slug===slug)!);return <><JsonLd data={{'@type':'Service','@id':siteUrl+'/services/'+s.slug+'#service',name:s.name,serviceType:s.name,description:s.summary,url:siteUrl+'/services/'+s.slug,provider:{'@id':siteUrl+'/#organization'}}}/><BreadcrumbData items={[{name:'Services',path:'/services'},{name:s.name,path:'/services/'+s.slug}]}/><Breadcrumb items={[{label:'Services',href:'/services'},{label:s.name}]}/><ServiceHero service={s}/><SolutionOverview slug={s.slug}/><section className="container inner-section split-section"><div><Tag>{s.name.toUpperCase()}</Tag><h2>What does our<br/>{s.name.toLowerCase()} service include?</h2></div><div><p className="large-copy">{s.intro}</p><div className="audience-note"><strong>A good fit for</strong><p>{s.audience}</p></div></div></section><section id="scope" className="container inner-section"><div className="section-top"><div><Tag>WHAT WE CAN HELP WITH</Tag><h2>{s.name}: the work involved.</h2></div><p>We shape the scope around your business, your priorities and the work that needs to happen next.</p></div><div className={`offering-grid service-offerings offerings-${serviceFamily(s.slug)}`}>{s.offerings.map(([title,text],i)=><article className="detail-panel" key={title}><span className="panel-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><ConversionBand title={`Need help with ${s.name.toLowerCase()}?`} text="Share your goals and current setup. We can help you define a practical scope." service={s.name}/><section className="container inner-section delivery-section"><div className="delivery-card"><Tag>WHAT YOU TAKE AWAY</Tag><h2>Clear work.<br/>Useful deliverables.</h2><Checklist items={s.deliverables}/><p className="small-note">Final deliverables, schedule and fees are agreed in your proposal.</p></div><div className="delivery-process"><Tag>HOW WE WORK</Tag><h2>From understanding<br/>to action.</h2>{guidance.steps.map(([t,d],i)=><div className="process-row" key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></section><section className="container inner-section faq-section"><div><Tag>COMMON QUESTIONS</Tag><h2>Your questions,<br/>answered.</h2></div><FAQ items={[[guidance.question,guidance.answer],...s.faq]}/></section><section className="container inner-section"><div className="section-top"><div><Tag>CONNECTED EXPERTISE</Tag><h2>Build on the right foundation.</h2></div><Link className="outline" href="/services">All Services <ArrowRight size={16}/></Link></div><div className="related-grid">{related.map(x=><ServiceCard service={x} key={x.slug}/>)}</div></section><CTA title={`Let’s talk ${s.name.toLowerCase()}.`}/></>}
