import {PlatformDirectory} from '../../../components/ServiceLanding';
import {serviceGroups} from '../../../lib/service-groups';
import type {Metadata} from 'next';
import Link from 'next/link';
import {ArrowRight} from 'lucide-react';
import {services} from '../../../lib/content';
import {Breadcrumb,PageHero,ServiceCard,CTA,Tag} from '../../../components/Inner';
export const metadata:Metadata={title:'Digital & Creative Services | Inventive Clicks',description:'Explore digital marketing, SEO, PPC, design, web development, e-commerce, content and remote staffing services.',alternates:{canonical:'/services'}};
export default function Services(){return <><Breadcrumb items={[{label:'Services'}]}/><PageHero eyebrow="OUR SERVICES" title="Digital marketing, design and website services." summary="Compare 30 services, from SEO and paid campaigns to websites and remote staffing. Each page explains the scope, deliverables and decisions involved." icon={0}><Link className="primary" href="#all-services">Find Your Service <ArrowRight size={18}/></Link></PageHero><section id="all-services" className="container inner-section"><div className="section-top"><div><Tag>BUILT AROUND YOUR GOALS</Tag><h2>Choose the support<br/>your project needs.</h2></div><p>Start with the service you need. We can connect the right disciplines around a shared objective.</p></div><nav className="service-category-links" aria-label="Service categories">{serviceGroups.map(group=><Link href={`#${group.id}`} key={group.id}>{group.name}</Link>)}</nav>{serviceGroups.map(group=><section className="service-category" id={group.id} key={group.id}><h2>{group.name}</h2><div className="inner-service-grid">{group.slugs.map(slug=><ServiceCard key={slug} service={services.find(s=>s.slug===slug)!}/>)}</div></section>)}</section><PlatformDirectory kind="commerce"/><PlatformDirectory kind="social"/><CTA title="Not sure where to start?" text="Tell us about the challenge. We’ll help you frame the right scope."/></>}
