'use client';
import {useEffect,useState} from 'react';
import {Download,CheckCircle2,MessageCircle} from 'lucide-react';
import {platforms} from '../lib/platforms';
import {services} from '../lib/content';
import {hasWhatsApp,whatsappHref} from '../lib/contact';
export default function BriefForm({career=false}:{career?:boolean}){
 const [saved,setSaved]=useState(false),[same,setSame]=useState(true),[phone,setPhone]=useState(''),[service,setService]=useState(''),[draft,setDraft]=useState('');
 useEffect(()=>{const value=new URLSearchParams(window.location.search).get('service');if(value&&[...services.map(s=>s.name),...platforms.map(p=>p.name+' Marketing')].includes(value))setService(value)},[]);
 function prepare(form:HTMLFormElement){const data=new FormData(form);if(same)data.set('WhatsApp',phone||'Not provided');return `INVENTIVE CLICKS: ${career?'CANDIDATE PROFILE':'PROJECT ENQUIRY'}\n\n${Array.from(data.entries()).map(([k,v])=>`${k}: ${v}`).join('\n\n')}`}
 return <form className="brief-form" onChange={()=>{setSaved(false);setDraft('')}} onSubmit={e=>{e.preventDefault();const text=prepare(e.currentTarget);const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=career?'inventive-clicks-candidate-profile.txt':'inventive-clicks-project-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setSaved(true)}}>
 <div className="form-pair"><label>Your name<input required autoComplete="name" name="Name" placeholder="Full name" maxLength={120}/></label><label>Email address<input required autoComplete="email" type="email" name="Email" placeholder="you@company.com" maxLength={254}/></label></div>
 <div className="form-pair"><label>Phone number <small>Optional · include country code</small><input type="tel" inputMode="tel" autoComplete="tel" name="Phone" placeholder="e.g. +92 3XX XXXXXXX" value={phone} onChange={e=>setPhone(e.target.value)} maxLength={25}/></label><label>Preferred way to contact you<select name="Contact preference"><option>Email</option><option>Phone call</option><option>WhatsApp</option></select></label></div>
 <div className="whatsapp-fields" id="whatsapp-contact"><label className="checkbox-label"><input type="checkbox" checked={same} onChange={e=>setSame(e.target.checked)}/> Use my phone number for WhatsApp</label>{!same&&<label>WhatsApp number <small>Optional · include country code</small><input type="tel" inputMode="tel" autoComplete="off" name="WhatsApp" placeholder="e.g. +92 3XX XXXXXXX" maxLength={25}/></label>}</div>
 {career?<><label>Your specialty<select required name="Specialty" defaultValue=""><option disabled value="">Select your area</option>{['Marketing & strategy','SEO & paid media','Design & branding','Content & social','Web development','Client services & operations'].map(x=><option key={x}>{x}</option>)}</select></label><div className="form-pair"><label>Portfolio or profile URL<input type="url" name="Portfolio" placeholder="https://…"/></label><label>Location and time zone<input name="Location" placeholder="City / time zone"/></label></div><label>Your experience and availability<textarea required rows={5} name="Experience" placeholder="Relevant experience, work samples and availability." maxLength={4000}/></label></>:<><label>Company or website<input name="Company" autoComplete="organization" placeholder="Your company or website" maxLength={200}/></label><div className="form-pair"><label>What can we help with?<select required name="Service" value={service} onChange={e=>setService(e.target.value)}><option disabled value="">Choose a service</option>{services.map(s=><option key={s.slug}>{s.name}</option>)}{platforms.map(p=><option key={p.slug}>{p.name} Marketing</option>)}<option>More than one service</option></select></label><label>Preferred timeline<select name="Timeline"><option>Let’s discuss</option><option>Within a month</option><option>1 to 3 months</option><option>3+ months</option></select></label></div><label>Tell us about your project<textarea required name="Project" rows={5} placeholder="What do you want to improve? Include your goals, current website and any deadline." maxLength={4000}/></label></>}
 <p className="form-note">{hasWhatsApp?'Save a copy, or review your details before opening WhatsApp. Nothing is sent until you send the message in WhatsApp.':'Save your brief with your preferred contact details. Direct WhatsApp chat is not connected yet; this form does not send an enquiry.'}</p>
 <div className="form-actions"><button className="primary" type="submit">{career?'Save Candidate Profile':'Save Project Brief'} <Download size={17}/></button>{hasWhatsApp&&<button className="whatsapp-link" type="button" onClick={e=>{const form=e.currentTarget.form!;if(form.reportValidity())setDraft(prepare(form))}}>Review for WhatsApp <MessageCircle size={18}/></button>}</div>
 {draft&&<div className="whatsapp-preview"><h3>Review your message</h3><p>Your name and contact details below will be included.</p><pre>{draft}</pre><a className="whatsapp-link" href={whatsappHref(draft)} target="_blank" rel="noopener noreferrer">Open WhatsApp <MessageCircle size={18}/></a></div>}
 {saved&&<p className="form-success" role="status"><CheckCircle2 size={18}/> Your download has started. Nothing has been submitted.</p>}
 </form>
}
