'use client';
import {serviceGroups} from '../lib/service-groups';
import Link from 'next/link';
import {useEffect,useState,useRef} from 'react';
import {usePathname} from 'next/navigation';
import {ArrowRight,Menu,X,ChevronDown} from 'lucide-react';
import {platforms} from '../lib/platforms';
import {services} from '../lib/content';
import {WhatsAppLink} from './ContactActions';
export function Brand(){return <Link className="logo" href="/" aria-label="Inventive Clicks home"><span className="brand-mark" aria-hidden="true"/><span>Inventive Clicks<small>Ideas. Strategy. Real Results.</small></span></Link>}
export function Header(){const path=usePathname();const [mobile,setMobile]=useState(false);const menu=useRef<HTMLDetailsElement>(null);useEffect(()=>{setMobile(false);if(menu.current)menu.current.open=false},[path]);useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMobile(false);if(menu.current)menu.current.open=false}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[]);return <header className="header"><div className="container nav"><Brand/><nav aria-label="Main navigation" id="main-navigation" className={mobile?'mobile-open':''}><Link href="/" aria-current={path==='/'?'page':undefined}>Home</Link><Link href="/about" aria-current={path==='/about'?'page':undefined}>About</Link><details className="nav-services" ref={menu}><summary>Services <ChevronDown size={13}/></summary><div className="mega-menu"><Link className="mega-heading" href="/services">Explore our services <ArrowRight size={17}/></Link><div className="mega-groups">{serviceGroups.map(group=><section className="mega-group" key={group.id}><h3><Link href={`/services#${group.id}`}>{group.name}</Link></h3>{group.slugs.map(slug=>{const s=services.find(s=>s.slug===slug)!;return <Link key={slug} href={`/services/${slug}`} aria-current={path===`/services/${slug}`?'page':undefined}>{s.name}</Link>})}</section>)}</div><section className="mega-platforms"><h3>Platform marketing: organic + paid</h3><nav aria-label="Platform marketing">{platforms.map(p=><Link key={p.slug} href={`/platforms/${p.slug}`}>{p.name}</Link>)}</nav></section></div></details>{[['Work','work'],['Careers','careers'],['Blog','blog']].map(([label,slug])=><Link key={slug} href={`/${slug}`} aria-current={path.startsWith('/'+slug)?'page':undefined}>{label}</Link>)}</nav><Link className="talk top-talk" href="/contact">Let’s Talk <ArrowRight size={19}/></Link><button className="mobile-toggle" aria-label={mobile?'Close menu':'Open menu'} aria-controls="main-navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>}
export function Footer(){return <footer className="container footer"><div className="footer-grid"><div className="footer-brand"><Brand/><p>A full-service digital agency helping brands grow through creativity, strategy, and performance.</p><Link className="footer-contact" href="/contact">Start a conversation <ArrowRight size={15}/></Link><WhatsAppLink className="footer-whatsapp"/></div><div><h3>Quick Links</h3>{[['Home',''],['About Us','about'],['Our Work','work'],['Careers','careers'],['Blog','blog'],['Contact','contact']].map(([name,slug])=><Link href={'/'+slug} key={name}>{name}</Link>)}</div><div><h3>Our Services</h3>{services.slice(0,10).map(s=><Link key={s.slug} href={`/services/${s.slug}`}>{s.name}</Link>)}<Link href="/services">Explore all 30 services <ArrowRight size={14}/></Link></div><div><h3>Ideas worth exploring.</h3><p>Practical thinking on marketing, design and building a stronger team.</p><Link className="outline footer-insights" href="/blog">Read our insights <ArrowRight size={16}/></Link></div></div><div className="footer-bottom"><span>© 2026 Inventive Clicks. All Rights Reserved.</span><div><Link href="/privacy-policy">Privacy Policy</Link><span>|</span><Link href="/terms-and-conditions">Terms & Conditions</Link></div></div></footer>}
